services:
  - type: web
    name: sparklawn-fleet-dashboard
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: FORD_TELEMATICS_CLIENT_ID
        sync: false
      - key: FORD_TELEMATICS_CLIENT_SECRET
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: JOBBER_ACCESS_TOKEN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://fleet.sparklawnnwa.com/auth/google/callback
      - key: SESSION_SECRET
        generateValue: true
